### ISSUE TITLE
I want to join XiongGuiHui

### ISSUE THREAD

**Issue by Martins3** [XiongGuiHui/Readings#7]
Leave your github username as a comment and check your email related to gtihub.com. If you come across anything problem, you can connect with `Martins3` with weixing(id:cjmmdf).

**Comment by BITxiao666** [comment]
北理工-肖子原: BITxiao666

**Comment by czshuai** [comment]
chenzeshuai

**Comment by nicolaswilde** [comment]
nicolaswilde
from UCAS 王重熙

**Comment by zhuweipu** [comment]
@Martins3 I haven't receive the email to join this repo

**Comment by Martins3** [comment]
@zhuweipu  I will do it again

**Comment by ict-hanQ7** [comment]
中科大-齐寒：ict-hanQ7

**Comment by Martins3** [comment]
It seems that everyone has joined the XiongGuiHui, so I closed this issue, if you still join this organization, please connect me with gmail(hubachelar@gmail.com)
